# numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
a=np.array([(1,2,3),(4,5,6)])

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
type(a)

numpy.ndarray

In [9]:
a.shape

(2, 3)

In [10]:
a.itemsize

4

In [11]:
a.size

6

In [12]:
a.itemsize*a.size

24

In [13]:
a.dtype

dtype('int32')

In [15]:
import sys

SIZE=1000

lst=range(SIZE)
print("LIST SIZE:", sys.getsizeof(5)*len(lst))

arr=np.arange(SIZE, dtype='int8')
print("ARRAY SIZE:", arr.itemsize*arr.size)

LIST SIZE: 28000
ARRAY SIZE: 1000


In [20]:
import time

SIZE=1000000

l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start=time.time()
result=[x+y for x,y in zip(l1,l2)]
end=time.time()
print("LIST TOOK:", (end-start)*1000)

start=time.time()
result=a1+a2
end=time.time()
print("ARRAY TOOK:", (end-start)*1000)

LIST TOOK: 88.70053291320801
ARRAY TOOK: 8.999109268188477


In [21]:
a=np.array([(1,2,3,4),(5,6,7,8)])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
a[1,1]

6

In [24]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [26]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
a[1,0:2]

array([4, 5])

In [31]:
print(a[1:,1:])

[[5 6]
 [8 9]]


In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a.sum()

45

In [34]:
a.min()

1

In [35]:
a.max()

9

In [36]:
a.sum(axis=0)

array([12, 15, 18])

In [37]:
a.sum(axis=1)

array([ 6, 15, 24])

In [38]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [39]:
np.std(a)

2.581988897471611

In [40]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [41]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [42]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [43]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [44]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [45]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# identity array

In [52]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a=np.array([1,2,3])

In [54]:
a

array([1, 2, 3])

In [55]:
print(a)

[1 2 3]


In [56]:
print(a+2)

[3 4 5]


In [57]:
print(a-2)

[-1  0  1]


In [58]:
print(a/2)

[0.5 1.  1.5]


In [59]:
print(a*5)

[ 5 10 15]


In [60]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
b=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [61]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a.shape

(3, 3)

In [64]:
b.shape

(3, 3)

In [65]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [66]:
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [68]:
x=np.array([(1,2,3),(3,4,5),(7,8,9)])
y=np.array([(1,2,3),(4,5,6)])

In [69]:
x.shape

(3, 3)

In [70]:
y.shape

(2, 3)

In [71]:
np.dot(x,y)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [72]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [73]:
np.pi

3.141592653589793

In [74]:
np.e

2.718281828459045